# Generated by Django 5.0 on 2023-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=55)),
                ('desc', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photo/')),
            ],
        ),
    ]
