# Generated by Django 5.0 on 2023-12-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=60, verbose_name=(('Mobile', 'mobile'), ('watch', 'watch'), ('laptop', 'laptop'))),
        ),
    ]
