# Generated by Django 5.0 on 2023-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'mobile'), ('watch', 'watch'), ('laptop', 'laptop')], max_length=6),
        ),
    ]
