# Generated by Django 5.0 on 2024-01-05 12:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('prod', django.db.models.manager.Manager()),
            ],
        ),
    ]
