# Generated by Django 5.0 on 2024-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0005_alter_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'mobile'), ('watch', 'watch'), ('laptop', 'laptop')], max_length=6),
        ),
    ]
