# Generated by Django 5.0 on 2024-01-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0013_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
